### ISSUE TITLE
Fail to use kong -portal-cli in my GitHub workflow

### ISSUE THREAD

**Issue by mintingchen** [Kong/kong-portal-cli#133]
Hi I am trying to use the portal-cli in my GitHub action workflow. For every push action to my kong-portal- templates, the workflow will deploy it to the Kong dev portal. But I am getting a `Internal Error: connect ETIMEDOUT at <kongserver_url>:8001 TCPConnectWrap.afterConnect github workflow`. If I run `portal deploy default` from my local machine, it works fine.

```
name: kong_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install portal cli
        run: npm install -g kong-portal-cli
          
      - name: deploy
        run: portal deploy default
```
